/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DexGovernor } from "./DexGovernor";
export type { GovernanceTimeLock } from "./GovernanceTimeLock";
export type { GovernanceToken } from "./GovernanceToken";
