/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DexGovernor__factory } from "./DexGovernor__factory";
export { GovernanceTimeLock__factory } from "./GovernanceTimeLock__factory";
export { GovernanceToken__factory } from "./GovernanceToken__factory";
