/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDexPool__factory } from "./IDexPool__factory";
export { IDexPoolFactory__factory } from "./IDexPoolFactory__factory";
